### ISSUE TITLE
Typescript types are missing

### ISSUE THREAD

**Issue by mariusbolik** [fresha/capacitor-plugin-googlepay#2]
First of all, thank you for this awesome plugin! Great work!!!

While working with this plugin, I discovered that the types are missing in the npm package. Please see the screenshot:

<img width="80%" alt="Bildschirmfoto 2022-09-09 um 12 00 36" src="https://user-images.githubusercontent.com/39862171/189325194-54bcea5a-c49f-4d3d-ba5a-72d9536191ce.png">

I hope for a fast solution.

Kind regards
Marius 😊

**Comment by kondratk** [comment]
Hey @mariusbolik! Thank you for noticing that bug. The issue should be solved now with v1.0.1: https://www.npmjs.com/package/@fresha/capacitor-plugin-googlepay

Also, if you are going to implement Apple Pay at your app, we have a plugin for that as well :) https://github.com/fresha/capacitor-plugin-applepay

**Comment by mariusbolik** [comment]
Hey @kondratk, thank you very much for your fast solution!
I'm already started working with the apple pay plugin. It's also very helpful for me! :D
